import { workflow, node, trigger, ifElse, expr, newCredential } from '@n8n/workflow-sdk'

// GENERATED by n8n/build-workflow.py from this template plus n8n/extract-triage-inputs.js
// and n8n/format-note.js. Edit the template or the JS, then regenerate.
//
// Triage Intercom EDI ticket
//
// An Intercom conversation arrives (webhook topic conversation.user.created). n8n reads the
// customer's words, pulls out the transaction id, document type, partners, statuses and
// error lines, and posts them to this repo's triage server (POST /triage). The result lands
// on the conversation as an internal note, four custom attributes and a tag, plus a Slack
// post. Nothing customer-facing is sent: the engineer reads the note and replies themselves.
// If a required input is missing the workflow asks for it in a note and stops. It never guesses.
// Every request is checked against X-Hub-Signature (HMAC-SHA1 of the raw body with the app
// client secret) before anything else runs. Unsigned requests are dropped, not answered.

// Bearer Auth credential in n8n; id from list_credentials({ type: 'httpBearerAuth' }).
const intercom = newCredential('Intercom (sandbox)', 'Cv5vxmy8jZD8B5dw')

// One retry policy for every network call. Transient 429s and blips get absorbed; the
// error output only fires on real failures.
const http = { retryOnFail: true, maxTries: 3, waitBetweenTries: 5000, onError: 'continueErrorOutput' }

const intercomAuth = {
  authentication: 'genericCredentialType',
  genericAuthType: 'httpBearerAuth',
  sendHeaders: true,
  headerParameters: {
    parameters: [
      { name: 'Intercom-Version', value: '2.16' },
      { name: 'Accept', value: 'application/json' },
    ],
  },
}

const jsonBodyBase = { sendBody: true, contentType: 'json', specifyBody: 'json' }

// ---------- Receive ----------

const intercomWebhook = trigger({
  type: 'n8n-nodes-base.webhook',
  version: 2.1,
  config: {
    name: 'Intercom webhook',
    parameters: {
      httpMethod: 'POST',
      path: 'intercom-conversation',
      // Intercom wants a 200 within 5 seconds or it retries. Answer first, work after.
      responseMode: 'onReceived',
      // Keep the exact bytes Intercom signed (binary property "data"); body is still parsed.
      options: { rawBody: true },
    },
    notes: 'Raw body kept as binary "data" so the signature check hashes the exact bytes Intercom signed. The parsed JSON body is still available.',
  },
  output: [{ headers: { 'x-hub-signature': 'sha1=0000' }, body: { topic: 'conversation.user.created', data: { item: { id: '123' } } } }],
})

// ---------- Verify ----------

const computeSignature = node({
  type: 'n8n-nodes-base.crypto',
  version: 1,
  config: {
    name: 'Compute signature',
    parameters: {
      action: 'hmac',
      type: 'SHA1',
      binaryData: true,
      binaryPropertyName: 'data',
      // The app client secret lives in the n8n container env, never in this file.
      secret: expr('{{ $env.INTERCOM_CLIENT_SECRET }}'),
      dataPropertyName: 'sig',
      encoding: 'hex',
    },
    notes: 'HMAC-SHA1 of the raw body with the Intercom app client secret (env INTERCOM_CLIENT_SECRET on both n8n containers).',
  },
  output: [{ sig: 'de7c9b85b8b78aa6bc8a7a36f70a90701c9db4d9' }],
})

const signatureValid = ifElse({
  version: 2.3,
  config: {
    name: 'Signature valid?',
    parameters: {
      options: {},
      conditions: {
        options: { version: 3, leftValue: '', caseSensitive: true, typeValidation: 'strict' },
        combinator: 'and',
        conditions: [
          {
            // Fails closed: no secret configured means nothing is trusted.
            id: 'secret-set',
            operator: { type: 'string', operation: 'notEmpty', singleValue: true },
            leftValue: expr("{{ $env.INTERCOM_CLIENT_SECRET || '' }}"),
            rightValue: '',
          },
          {
            id: 'signature-matches',
            operator: { type: 'string', operation: 'equals' },
            leftValue: expr("{{ 'sha1=' + $json.sig }}"),
            rightValue: expr("{{ $('Intercom webhook').item.json.headers['x-hub-signature'] || '' }}"),
          },
        ],
      },
    },
    notes: 'ponytail: plain string equals, not constant-time. Upgrade path: a Code node with crypto.timingSafeEqual once NODE_FUNCTION_ALLOW_BUILTIN includes crypto.',
  },
})

const rejectBadSignature = node({
  type: 'n8n-nodes-base.noOp',
  version: 1,
  config: {
    name: 'Reject: bad signature',
    parameters: {},
    notes: 'The webhook already answered 200. Unsigned or wrongly signed requests stop here and touch nothing.',
  },
  output: [{}],
})

const isNewCustomerConversation = ifElse({
  version: 2.3,
  config: {
    name: 'Is new customer conversation?',
    parameters: {
      options: {},
      conditions: {
        options: { version: 3, leftValue: '', caseSensitive: true, typeValidation: 'strict' },
        combinator: 'and',
        conditions: [
          {
            id: 'topic',
            operator: { type: 'string', operation: 'equals' },
            leftValue: expr("{{ $('Intercom webhook').item.json.body.topic }}"),
            rightValue: 'conversation.user.created',
          },
        ],
      },
    },
  },
})

const ignoreOtherTopics = node({
  type: 'n8n-nodes-base.noOp',
  version: 1,
  config: { name: 'Ignore other topics', parameters: {} },
  output: [{}],
})

// ---------- Read ticket ----------

const fetchConversation = node({
  type: 'n8n-nodes-base.httpRequest',
  version: 4.5,
  config: {
    name: 'Fetch conversation',
    parameters: {
      method: 'GET',
      // display_as=plaintext: Intercom strips the HTML for us.
      url: expr("{{ 'https://api.intercom.io/conversations/' + $('Intercom webhook').item.json.body.data.item.id + '?display_as=plaintext' }}"),
      ...intercomAuth,
      options: { timeout: 10000 },
    },
    credentials: { httpBearerAuth: intercom },
    ...http,
  },
  output: [{ id: '123', source: { body: 'Transaction id: ...' }, conversation_parts: { conversation_parts: [] } }],
})

const extractTriageInputs = node({
  type: 'n8n-nodes-base.set',
  version: 3.5,
  config: {
    name: 'Extract triage inputs',
    parameters: {
      mode: 'manual',
      assignments: {
        assignments: [
          {
            id: 'r',
            name: 'result',
            type: 'object',
            value: expr(`{{ (() => {
    function extractTriageInputs(conv) {
      const parts = ((conv.conversation_parts || {}).conversation_parts || [])
        .filter((p) => p.author && p.author.type === "user" && p.body)
        .map((p) => p.body);
      const text = [(conv.source || {}).body || ""].concat(parts).join("\\n\\n").trim();

      const pick = (re) => { const m = text.match(re); return m ? m[1] : undefined; };
      const upper = (v) => (v ? v.toUpperCase() : undefined);

      const id = pick(/\\b([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})\\b/i);
      const docType = pick(/\\b(\\d{3}_[A-Z_]+)\\b/) || pick(/\\bdocument\\s+(\\S+?)[,.\\s]/i);
      const senderId = pick(/\\bsender\\s+([A-Z0-9_-]+)/i);
      const receiverId = pick(/\\breceiver\\s+([A-Z0-9_-]+)/i);
      const direction = (pick(/\\bdirection\\s+(in|out)\\b/i) || "in").toLowerCase();
      const stream = (pick(/\\bstream\\s+(test|live)\\b/i) || "live").toLowerCase();

      const VALID = ["PROCESSING", "VALID", "INVALID"];
      const DELIV = ["PENDING", "SENT", "DELIVERED", "FAILED"];
      const ACK = ["NOT_ACKNOWLEDGED", "ACCEPTED_WITH_ERRORS", "ACCEPTED", "REJECTED", "OVERDUE"];
      const status = (label, allowed) => {
        const v = upper(pick(new RegExp("\\\\b" + label + "\\\\s+([A-Z_]+|nothing)", "i")));
        return allowed.indexOf(v) >= 0 ? v : undefined;
      };
      let validationStatus = status("validation", VALID);
      const neverCreated = /validation\\s+nothing|never created/i.test(text);
      const deliveryStatus = status("delivery", DELIV);
      const acknowledgmentStatus = status("acknowledgment", ACK);

      const errors = [];
      const errRe = /^\\s*Error:\\s*(.+)$/gim;
      let m;
      while ((m = errRe.exec(text)) !== null) errors.push({ message: m[1].trim(), source: "guideline" });

      const missing = [];
      if (!id) missing.push("transaction id");
      if (!docType) missing.push("document type (e.g. 850_PURCHASE_ORDER)");
      if (!senderId) missing.push("sender id");
      if (!receiverId) missing.push("receiver id");

      const tx = { id, ediTransactionType: docType, senderId, receiverId, direction, stream, errors, customer_note: text };
      if (validationStatus) tx.validationStatus = validationStatus;
      else if (neverCreated) tx.validationStatus = null;
      if (deliveryStatus) tx.deliveryStatus = deliveryStatus;
      if (acknowledgmentStatus) tx.acknowledgmentStatus = acknowledgmentStatus;
      return { tx, missing, conversation_id: String(conv.id || "") };
    }
    return extractTriageInputs($('Fetch conversation').item.json)
})() }}`),
          },
        ],
      },
      options: {},
    },
    notes: 'Output: { tx, missing[], conversation_id }. Read by several downstream nodes, which is why it is a Set and not inlined. Source: n8n/extract-triage-inputs.js.',
  },
  output: [{ result: { tx: { id: 'x' }, missing: [], conversation_id: '123' } }],
})

const lookUpAdminId = node({
  type: 'n8n-nodes-base.httpRequest',
  version: 4.5,
  config: {
    name: 'Look up admin id',
    parameters: {
      method: 'GET',
      url: 'https://api.intercom.io/me',
      ...intercomAuth,
      options: { timeout: 10000 },
    },
    notes: 'Notes need an admin_id. One cheap call beats a config value someone forgets to set.',
    credentials: { httpBearerAuth: intercom },
    ...http,
  },
  output: [{ id: '1', type: 'admin' }],
})

const hasAllRequiredInputs = ifElse({
  version: 2.3,
  config: {
    name: 'Has all required inputs?',
    parameters: {
      options: {},
      conditions: {
        options: { version: 3, leftValue: '', caseSensitive: true, typeValidation: 'strict' },
        combinator: 'and',
        conditions: [
          {
            id: 'missing',
            operator: { type: 'number', operation: 'equals' },
            leftValue: expr("{{ $('Extract triage inputs').item.json.result.missing.length }}"),
            rightValue: 0,
          },
        ],
      },
    },
  },
})

const askForMissingInputs = node({
  type: 'n8n-nodes-base.httpRequest',
  version: 4.5,
  config: {
    name: 'Note: ask for missing inputs',
    parameters: {
      method: 'POST',
      url: expr("{{ 'https://api.intercom.io/conversations/' + $('Extract triage inputs').item.json.result.conversation_id + '/reply' }}"),
      ...intercomAuth,
      ...jsonBodyBase, jsonBody: expr(`{{ (() => {
    // Internal note only (message_type note). Lists what the triage still needs. Never guesses.
    const missing = $('Extract triage inputs').item.json.result.missing
    const body = '<p><b>EDI triage</b> cannot start yet. Missing: ' + missing.join(', ') + '.</p>'
      + '<p>Ask the customer for these, or read them off the transaction (Validation Errors tab: add ?tab=errors to the transaction URL).</p>'
    return JSON.stringify({ message_type: 'note', type: 'admin', admin_id: String($('Look up admin id').item.json.id), body })
})() }}`),
      options: { timeout: 10000 },
    },
    credentials: { httpBearerAuth: intercom },
    ...http,
  },
  output: [{ id: 'note1' }],
})

// ---------- Triage ----------

const runTriage = node({
  type: 'n8n-nodes-base.httpRequest',
  version: 4.5,
  config: {
    name: 'Run triage',
    parameters: {
      method: 'POST',
      url: 'http://host.docker.internal:8001/triage',
      ...jsonBodyBase, jsonBody: expr("{{ JSON.stringify($('Extract triage inputs').item.json.result.tx) }}"),
      options: { timeout: 30000 },
    },
    notes: 'Classification is code, not the model. The server ranks causes and drafts the reply; BEDROCK_MOCK=true returns the fixture result.',
    ...http,
  },
  output: [{ transaction_id: 'x', tier: 'mosaic', classification: 'invalid.guideline', mode: 'mock', hypotheses: [], customer_reply: '', ticket_two: { kind: 'rule', effort: 'S', title: '', why: '' } }],
})

// ---------- Write back to Intercom ----------

const formatInternalNote = node({
  type: 'n8n-nodes-base.set',
  version: 3.5,
  config: {
    name: 'Format internal note',
    parameters: {
      mode: 'manual',
      assignments: {
        assignments: [
          {
            id: 'n',
            name: 'note_html',
            type: 'string',
            value: expr(`{{ (() => {
    function escapeHtml(v) {
      return String(v == null ? "" : v)
        .replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
        .replace(/"/g, "&quot;").replace(/'/g, "&#x27;");
    }
    function formatNote(r) {
      const e = escapeHtml;
      const lines = [
        "<b>EDI triage</b> for " + e(r.transaction_id) + ": tier " + e(r.tier) +
          ", classification " + e(r.classification) + ", mode " + e(r.mode),
        "<b>Hypotheses</b>",
      ];
      for (const h of r.hypotheses || []) {
        lines.push(h.rank + ". [" + e(h.confidence) + "] " + e(h.hypothesis));
        if (h.evidence && h.evidence.length) lines.push("&nbsp;&nbsp;evidence: " + e(h.evidence.join(", ")));
        if (h.check) lines.push("&nbsp;&nbsp;check: " + e(h.check));
      }
      const t = r.ticket_two || {};
      lines.push("<b>Draft customer reply</b> (not sent, send it yourself from the reply box)");
      lines.push(e(r.customer_reply));
      lines.push("<b>Ticket two</b> [" + e(t.kind) + ", effort " + e(t.effort) + "]: " + e(t.title));
      lines.push(e(t.why));
      return lines.map((l) => "<p>" + l + "</p>").join("");
    }
    return formatNote($('Run triage').item.json)
})() }}`),
          },
          { id: 't', name: 'tag_name', type: 'string', value: expr("{{ 'edi:' + $('Run triage').item.json.classification }}") },
        ],
      },
      options: {},
    },
    notes: 'Same HTML as intercom_bridge.format_note, every field escaped. Source: n8n/format-note.js.',
  },
  output: [{ note_html: '<p>...</p>', tag_name: 'edi:invalid.guideline' }],
})

const postInternalNote = node({
  type: 'n8n-nodes-base.httpRequest',
  version: 4.5,
  config: {
    name: 'Post internal note',
    parameters: {
      method: 'POST',
      url: expr("{{ 'https://api.intercom.io/conversations/' + $('Extract triage inputs').item.json.result.conversation_id + '/reply' }}"),
      ...intercomAuth,
      ...jsonBodyBase, jsonBody: expr("{{ JSON.stringify({ message_type: 'note', type: 'admin', admin_id: String($('Look up admin id').item.json.id), body: $('Format internal note').item.json.note_html }) }}"),
      options: { timeout: 10000 },
    },
    notes: 'message_type note keeps it off the customer screen. This workflow never replies, assigns, closes or snoozes.',
    credentials: { httpBearerAuth: intercom },
    ...http,
  },
  output: [{ id: 'note2' }],
})

const setConversationAttributes = node({
  type: 'n8n-nodes-base.httpRequest',
  version: 4.5,
  config: {
    name: 'Set conversation attributes',
    parameters: {
      method: 'PUT',
      url: expr("{{ 'https://api.intercom.io/conversations/' + $('Extract triage inputs').item.json.result.conversation_id }}"),
      ...intercomAuth,
      ...jsonBodyBase, jsonBody: expr(`{{ (() => {
    // The four attributes must exist in the workspace first (see n8n/README.md).
    const r = $('Run triage').item.json
    const top = (r.hypotheses && r.hypotheses[0]) ? r.hypotheses[0].confidence : 'low'
    return JSON.stringify({ custom_attributes: {
      edi_leaf: r.classification, edi_tier: r.tier, edi_confidence: top, edi_ticket_two_kind: r.ticket_two.kind,
    } })
})() }}`),
      options: { timeout: 10000 },
    },
    credentials: { httpBearerAuth: intercom },
    ...http,
  },
  output: [{ id: '123' }],
})

const createOrGetTag = node({
  type: 'n8n-nodes-base.httpRequest',
  version: 4.5,
  config: {
    name: 'Create or get tag',
    parameters: {
      method: 'POST',
      url: 'https://api.intercom.io/tags',
      ...intercomAuth,
      ...jsonBodyBase, jsonBody: expr("{{ JSON.stringify({ name: $('Format internal note').item.json.tag_name }) }}"),
      options: { timeout: 10000 },
    },
    notes: 'POST /tags is create-or-update by name, so it doubles as the lookup.',
    credentials: { httpBearerAuth: intercom },
    ...http,
  },
  output: [{ id: 'tag1', name: 'edi:invalid.guideline' }],
})

const attachTag = node({
  type: 'n8n-nodes-base.httpRequest',
  version: 4.5,
  config: {
    name: 'Attach tag',
    parameters: {
      method: 'POST',
      url: expr("{{ 'https://api.intercom.io/conversations/' + $('Extract triage inputs').item.json.result.conversation_id + '/tags' }}"),
      ...intercomAuth,
      ...jsonBodyBase, jsonBody: expr("{{ JSON.stringify({ id: String($('Create or get tag').item.json.id), admin_id: String($('Look up admin id').item.json.id) }) }}"),
      options: { timeout: 10000 },
    },
    credentials: { httpBearerAuth: intercom },
    ...http,
  },
  output: [{ id: 'tag1' }],
})

// ---------- Notify ----------

const formatSlackMessage = node({
  type: 'n8n-nodes-base.set',
  version: 3.5,
  config: {
    name: 'Format Slack message',
    parameters: {
      mode: 'manual',
      assignments: {
        assignments: [
          { id: 'c', name: 'slack_channel', type: 'string', value: '#edi-support' },
          {
            id: 's',
            name: 'slack_text',
            type: 'string',
            value: expr(`{{ (() => {
    const r = $('Run triage').item.json
    const top = (r.hypotheses && r.hypotheses[0]) || { hypothesis: '(no hypothesis)', confidence: 'low' }
    return ':mag: *EDI triage* ' + r.classification + ' (' + r.tier + ', ' + r.mode + ')'
      + ' on Intercom conversation ' + $('Extract triage inputs').item.json.result.conversation_id
      + '\\n> ' + top.hypothesis + ' [' + top.confidence + ']'
      + '\\nTicket two: ' + r.ticket_two.kind + ' (' + r.ticket_two.effort + ') ' + r.ticket_two.title
})() }}`),
          },
        ],
      },
      includeOtherFields: true,
      options: {},
    },
  },
  output: [{ slack_channel: '#edi-support', slack_text: ':mag: ...' }],
})

const buildErrorSummary = node({
  type: 'n8n-nodes-base.set',
  version: 3.5,
  config: {
    name: 'Build error summary',
    parameters: {
      mode: 'manual',
      assignments: {
        assignments: [
          { id: 'c', name: 'slack_channel', type: 'string', value: '#edi-support' },
          {
            id: 's',
            name: 'slack_text',
            type: 'string',
            // The webhook already answered 200, so the only place an error can go is here.
            value: expr("{{ ':x: *EDI triage workflow failed* at ' + $prevNode.name + ': ' + ($json.error && $json.error.message ? $json.error.message : JSON.stringify($json).slice(0, 300)) }}"),
          },
        ],
      },
      includeOtherFields: false,
      options: {},
    },
  },
  output: [{ slack_channel: '#edi-support', slack_text: ':x: ...' }],
})

const slackConfigured = ifElse({
  version: 2.3,
  config: {
    name: 'Slack configured?',
    parameters: {
      options: {},
      conditions: {
        options: { version: 3, leftValue: '', caseSensitive: true, typeValidation: 'loose' },
        combinator: 'and',
        conditions: [
          {
            id: 'has-webhook-url',
            operator: { type: 'string', operation: 'notEmpty', singleValue: true },
            leftValue: expr("{{ $env.SLACK_WEBHOOK_URL || '' }}"),
            rightValue: '',
          },
        ],
      },
    },
    notes: 'Unset SLACK_WEBHOOK_URL (CI, clean checkouts) falls back to the mocked node.',
  },
})

const postToSlackLive = node({
  type: 'n8n-nodes-base.httpRequest',
  version: 4.5,
  config: {
    name: 'Post to Slack (live)',
    parameters: {
      method: 'POST',
      url: expr('{{ $env.SLACK_WEBHOOK_URL }}'),
      ...jsonBodyBase, jsonBody: expr('{{ JSON.stringify({ text: $json.slack_text }) }}'),
      options: { timeout: 10000 },
    },
    retryOnFail: true,
    maxTries: 3,
    waitBetweenTries: 5000,
  },
  output: [{ ok: true }],
})

const postToSlackMocked = node({
  type: 'n8n-nodes-base.set',
  version: 3.5,
  config: {
    name: 'Post to Slack (mocked)',
    parameters: {
      mode: 'manual',
      assignments: {
        assignments: [
          { id: 'm', name: 'mocked', type: 'boolean', value: true },
          { id: 'ch', name: 'would_post_channel', type: 'string', value: expr('{{ $json.slack_channel }}') },
          { id: 'tx', name: 'would_post_text', type: 'string', value: expr('{{ $json.slack_text }}') },
        ],
      },
      includeOtherFields: true,
      options: {},
    },
  },
  output: [{ mocked: true }],
})

// ---------- Wiring ----------

export default workflow('edi-ticket-triage', 'Triage Intercom EDI ticket')
  .add(intercomWebhook)
  .to(computeSignature)
  .to(signatureValid
    .onTrue(isNewCustomerConversation
      .onTrue(fetchConversation
        .to(extractTriageInputs)
        .to(lookUpAdminId)
        .to(hasAllRequiredInputs
          .onTrue(runTriage.to(formatInternalNote).to(postInternalNote).to(setConversationAttributes)
            .to(createOrGetTag).to(attachTag).to(formatSlackMessage)
            .to(slackConfigured.onTrue(postToSlackLive).onFalse(postToSlackMocked)))
          .onFalse(askForMissingInputs)))
      .onFalse(ignoreOtherTopics))
    .onFalse(rejectBadSignature))
  // Every network call's error output goes to one summary, then the same Slack switch.
  .add(fetchConversation.output(1).to(buildErrorSummary))
  .add(lookUpAdminId.output(1).to(buildErrorSummary))
  .add(askForMissingInputs.output(1).to(buildErrorSummary))
  .add(runTriage.output(1).to(buildErrorSummary))
  .add(postInternalNote.output(1).to(buildErrorSummary))
  .add(setConversationAttributes.output(1).to(buildErrorSummary))
  .add(createOrGetTag.output(1).to(buildErrorSummary))
  .add(attachTag.output(1).to(buildErrorSummary))
  .add(buildErrorSummary.to(slackConfigured))
